import { writeText, yamlScalar } from './io.ts'
import { overlayPath } from './paths.ts'
import { runtimePluginSpecifier } from './plugin.ts'
import type { PluginManifest } from './types.ts'

export function renderOverlay(plugin: PluginManifest): string {
  const lines = [
    '# generated by dshx — do not commit',
    '# browser packages use their profile-linked package name; source-only plugins stay absolute',
    '- insert:',
    `    - id: ${plugin.id}`,
    `      name: ${yamlScalar(runtimePluginSpecifier(plugin))}`,
  ]
  if (plugin.config && Object.keys(plugin.config).length > 0) {
    lines.push('      config:')
    for (const [key, value] of Object.entries(plugin.config)) {
      lines.push(`        ${key}: ${JSON.stringify(value)}`)
    }
  }
  lines.push('')
  return lines.join('\n')
}

export function writeOverlay(root: string, plugin: PluginManifest): string {
  const path = overlayPath(root, plugin.id)
  writeText(path, renderOverlay(plugin))
  return path
}
